"""Initial schema

Revision ID: ed3d31fb01be
Revises: 
Create Date: 2026-03-19 09:18:38.871042

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed3d31fb01be"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_password_reset_otps_email"), table_name="password_reset_otps"
    )
    op.drop_index(op.f("ix_password_reset_otps_id"), table_name="password_reset_otps")
    op.drop_table("password_reset_otps")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_reset_otps",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("otp", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("password_reset_otps_pkey")),
    )
    op.create_index(
        op.f("ix_password_reset_otps_id"), "password_reset_otps", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_password_reset_otps_email"),
        "password_reset_otps",
        ["email"],
        unique=False,
    )
    # ### end Alembic commands ###
